<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-03-31 12:35
=======
# Generated by Django 5.1.7 on 2025-03-31 11:32
>>>>>>> shanta
=======
# Generated by Django 5.1.7 on 2025-03-31 11:32
>>>>>>> 95dd68ca27ac6253aae25b8daf48edec9541b4b9

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
